---
- name: Setup Ubuntu with Docker and OWASP OWTF
  hosts: localhost
  become: true
  tasks:

    - name: Set up logging environment variables
      ansible.builtin.set_fact:
        ANSIBLE_STDOUT_CALLBACK: yaml
        ANSIBLE_LOG_PATH: ~/ansible-playbook.log
      become: false

    - name: Update apt repository and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
          - docker-compose
          - make
        state: present

    - name: Add Docker's official GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker's stable repository
      ansible.builtin.shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt package index (again)
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker CE
      ansible.builtin.shell: |
        sudo apt-cache policy docker-ce && sudo apt install docker-ce -y

    - name: Add $USER to docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Notify user of need to log out and back in
      ansible.builtin.debug:
        msg: "NOTE: You'll need to log out and log back in for the group membership to take effect."

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started

    - name: Clone OWTF repository
      ansible.builtin.git:
        repo: https://github.com/owtf/owtf.git
        dest: "/home/{{ lookup('env', 'USER') }}/owtf"

    - name: Run OWTF using Docker Compose
      ansible.builtin.shell: |
        cd /home/{{ lookup('env', 'USER') }}/owtf && docker-compose -f docker/docker-compose.dev.yml up --build -d

    - name: Notify where logs can be found
      ansible.builtin.debug:
        msg: "Logs for this playbook execution can be found at ~/ansible-playbook.log."
